name: Deploy to UIT-WIKI.github.io repo
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # 指定 Python 版本

      - name: Install MkDocs dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs  # 安装 MkDocs 核心
          # 如需其他插件（如 mkdocs-material），补充安装：
          # pip install mkdocs-material

      - name: Build MkDocs site
        run: mkdocs build  # 生成静态站点到 site/ 目录（默认）

      - name: Deploy to target repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: DLUTCI-UIT/UIT-WIKI.github.io
          publish_dir: ./site  # MkDocs 构建输出目录（默认是 site/）
          publish_branch: main
          token: ${{ secrets.ORG_PAT }}
